"""add datacenter ip_address

Revision ID: 4a01a4473aba
Revises: be92d6134c1a
Create Date: 2026-09-11 02:03:07.452703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a01a4473aba'
down_revision: Union[str, None] = 'be92d6134c1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datacenters', sa.Column('ip_address', sa.String(length=45), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('datacenters', 'ip_address')
    # ### end Alembic commands ###
