"""multi-IP topology: TargetDatacenterIp, drop single-IP fields

Revision ID: 9c2f44ac8658
Revises: ba705fbfe6a7
Create Date: 2026-09-11 15:13:55.992054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9c2f44ac8658'
down_revision: Union[str, None] = 'ba705fbfe6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('target_datacenter_ips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dns_target_id', sa.Integer(), nullable=False),
    sa.Column('datacenter_id', sa.Integer(), nullable=False),
    sa.Column('slot_index', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('cloudflare_record_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['datacenter_id'], ['datacenters.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['dns_target_id'], ['dns_targets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dns_target_id', 'datacenter_id', 'slot_index', name='uq_target_dc_ip_slot')
    )
    op.create_index(op.f('ix_target_datacenter_ips_datacenter_id'), 'target_datacenter_ips', ['datacenter_id'], unique=False)
    op.create_index(op.f('ix_target_datacenter_ips_dns_target_id'), 'target_datacenter_ips', ['dns_target_id'], unique=False)
    op.add_column('audit_log_entries', sa.Column('slot_results', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('audit_log_entries', 'cloudflare_record_id')
    op.drop_column('datacenters', 'ip_address')
    op.drop_column('dns_targets', 'cloudflare_record_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dns_targets', sa.Column('cloudflare_record_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('datacenters', sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True))
    op.add_column('audit_log_entries', sa.Column('cloudflare_record_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.drop_column('audit_log_entries', 'slot_results')
    op.drop_index(op.f('ix_target_datacenter_ips_dns_target_id'), table_name='target_datacenter_ips')
    op.drop_index(op.f('ix_target_datacenter_ips_datacenter_id'), table_name='target_datacenter_ips')
    op.drop_table('target_datacenter_ips')
    # ### end Alembic commands ###
