"""audit log: nullable previous_datacenter_id, add rollback_of_id

Revision ID: ba705fbfe6a7
Revises: 4a01a4473aba
Create Date: 2026-09-11 03:04:33.448937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba705fbfe6a7'
down_revision: Union[str, None] = '4a01a4473aba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_log_entries', sa.Column('rollback_of_id', sa.Integer(), nullable=True))
    op.alter_column('audit_log_entries', 'previous_datacenter_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_audit_log_entries_rollback_of_id'), 'audit_log_entries', ['rollback_of_id'], unique=False)
    op.create_foreign_key(
        'fk_audit_log_entries_rollback_of_id',
        'audit_log_entries', 'audit_log_entries', ['rollback_of_id'], ['id'], ondelete='SET NULL'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_audit_log_entries_rollback_of_id', 'audit_log_entries', type_='foreignkey')
    op.drop_index(op.f('ix_audit_log_entries_rollback_of_id'), table_name='audit_log_entries')
    op.alter_column('audit_log_entries', 'previous_datacenter_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('audit_log_entries', 'rollback_of_id')
    # ### end Alembic commands ###
