"""initial schema

Revision ID: be92d6134c1a
Revises: 
Create Date: 2026-09-11 01:49:45.714908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be92d6134c1a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datacenters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('active', 'standby', 'disabled', name='datacenter_status'), server_default='active', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('domains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('cloudflare_zone_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('switch_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('dns_targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('record_type', sa.Enum('A', 'AAAA', 'CNAME', name='dns_record_type'), nullable=False),
    sa.Column('cloudflare_record_id', sa.String(length=64), nullable=True),
    sa.Column('current_datacenter_id', sa.Integer(), nullable=True),
    sa.Column('proxied', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['current_datacenter_id'], ['datacenters.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain_id', 'name', 'record_type', name='uq_dns_targets_domain_name_type')
    )
    op.create_index(op.f('ix_dns_targets_current_datacenter_id'), 'dns_targets', ['current_datacenter_id'], unique=False)
    op.create_index(op.f('ix_dns_targets_domain_id'), 'dns_targets', ['domain_id'], unique=False)
    op.create_table('audit_log_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('action_type', sa.Enum('single', 'bulk', 'rollback', name='audit_action_type'), nullable=False),
    sa.Column('dns_target_id', sa.Integer(), nullable=True),
    sa.Column('switch_group_id', sa.Integer(), nullable=True),
    sa.Column('previous_datacenter_id', sa.Integer(), nullable=False),
    sa.Column('new_datacenter_id', sa.Integer(), nullable=False),
    sa.Column('cloudflare_record_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('success', 'failed', 'rolled_back', name='audit_status'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['dns_target_id'], ['dns_targets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['new_datacenter_id'], ['datacenters.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['previous_datacenter_id'], ['datacenters.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['switch_group_id'], ['switch_groups.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_entries_created_at'), 'audit_log_entries', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_log_entries_dns_target_id'), 'audit_log_entries', ['dns_target_id'], unique=False)
    op.create_index(op.f('ix_audit_log_entries_switch_group_id'), 'audit_log_entries', ['switch_group_id'], unique=False)
    op.create_table('switch_group_members',
    sa.Column('switch_group_id', sa.Integer(), nullable=False),
    sa.Column('dns_target_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dns_target_id'], ['dns_targets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['switch_group_id'], ['switch_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('switch_group_id', 'dns_target_id')
    )
    op.create_index(op.f('ix_switch_group_members_dns_target_id'), 'switch_group_members', ['dns_target_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_switch_group_members_dns_target_id'), table_name='switch_group_members')
    op.drop_table('switch_group_members')
    op.drop_index(op.f('ix_audit_log_entries_switch_group_id'), table_name='audit_log_entries')
    op.drop_index(op.f('ix_audit_log_entries_dns_target_id'), table_name='audit_log_entries')
    op.drop_index(op.f('ix_audit_log_entries_created_at'), table_name='audit_log_entries')
    op.drop_table('audit_log_entries')
    op.drop_index(op.f('ix_dns_targets_domain_id'), table_name='dns_targets')
    op.drop_index(op.f('ix_dns_targets_current_datacenter_id'), table_name='dns_targets')
    op.drop_table('dns_targets')
    op.drop_table('switch_groups')
    op.drop_table('domains')
    op.drop_table('datacenters')
    # ### end Alembic commands ###
    # Autogenerate does not emit DROP TYPE for Postgres enums; without this,
    # a downgrade-then-upgrade cycle fails with "type already exists".
    sa.Enum(name='audit_action_type').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='audit_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='dns_record_type').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='datacenter_status').drop(op.get_bind(), checkfirst=True)
